# Lint Python
name: Python Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install uv
        uses: astral-sh/setup-uv@2ddd2b9cb38ad8efd50337e8ab201519a34c9f24 # v7
      - name: Install requirements
        run: uv sync --all-groups
      - name: Run ruff check
        run: uv run ruff check .
      - name: Run ruff format
        run: uv run ruff format --check .
      - name: Run mypy
        run: uv run mypy .
