# Lint Python
name: Python Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          submodules: recursive
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install requirements
        run: uv sync --all-groups
      - name: Run ruff check
        run: uv run ruff check .
      - name: Run ruff format
        run: uv run ruff format --check .
      - name: Run mypy
        run: uv run mypy .
