# Lint Python
name: Python Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          submodules: recursive
      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
      - name: Install requirements
        run: uv sync --all-groups
      - name: Run ruff check
        run: uv run ruff check .
      - name: Run ruff format
        run: uv run ruff format --check .
      - name: Run mypy
        run: uv run mypy .
